name: Delete Old Tags

on:
  workflow_dispatch:  # Adds the manual trigger

jobs:
  delete_tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all tags
        run: git fetch --tags

      - name: Delete tags older than 24 hours
        run: |
          current_time=$(date +%s)
          current_time_human=$(date -d @$current_time "+%Y-%m-%d %H:%M:%S")
          echo "Current Time: $current_time_human"
          one_day_ago=$(($current_time - 86400))  # 86400 seconds in 24 hours
          one_day_ago_human=$(date -d @$one_day_ago "+%Y-%m-%d %H:%M:%S")
          echo "One Day Ago: $one_day_ago_human"
          git for-each-ref --sort=taggerdate --format '%(refname:short) %(taggerdate:unix)' refs/tags | while read tag tag_time
          do
            tag_time_human=$(date -d @$tag_time "+%Y-%m-%d %H:%M:%S")
            echo "Processing tag: $tag with timestamp: $tag_time_human"
            if [ $tag_time -lt $one_day_ago ]; then
              echo "Deleting tag: $tag"
              git tag -d $tag
              git push origin :refs/tags/$tag
              echo "Deleted tag $tag"
            else
              echo "Tag $tag is newer than one day, keeping it."
            fi
          done
