name: Delete Old Tags

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once every 24 hours, at midnight UTC
  workflow_dispatch:  # Adds the manual trigger

jobs:
  delete_tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch all tags
        run: git fetch --tags

      - name: Delete tags older than 24 hours
        run: |
          current_time=$(date +%s)
          echo "Current Time: $current_time"
          one_day_ago=$(($current_time - 86400))  # 86400 seconds in 24 hours
          echo "One Day Ago: $one_day_ago"
          git for-each-ref --sort=taggerdate --format '%(refname:short) %(taggerdate:unix)' refs/tags | while read tag tag_time
          do
            echo "Processing tag: $tag with timestamp: $tag_time"
            if [ $tag_time -lt $one_day_ago ]; then
              echo "Deleting tag: $tag"
              git tag -d $tag
              git push origin :refs/tags/$tag
              echo "Deleted tag $tag"
            else
              echo "Tag $tag is newer than one day, keeping it."
            fi
          done
